[toolchain]
channel = "nightly-2025-12-01"
components = ["rust-src", "rust-analyzer", "miri", "clippy"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu"]
